### ISSUE TITLE
Error notification handler

### ISSUE THREAD

**Issue by Ilphrin** [dorcy-v/cpp_accessor#2]
When launching :Accessor on a C++ attibute a get this error message from neovim:
    no notification handler regsitered for "/home/pellet_k/.vim/bundle/cpp_accessor/rplugin/python3/cpp_getset:command:Accessor"

Not sure how exactly launch this command.

**Comment by dorcy-v** [comment]
Fix in a81c04787061d06bcd20ab897b32363c38d1e406
